trigger: master

variables:
- group: acr-credentials
- group: jira-credentials
- name: nodeVersion
  value: '22.2.0'

stages:
- template: ci-stage.yml # Triggers staging deployment
- template: tests-stage.yml
- template: notify-tester.yml
- template: swap-slots.yml # After succesful tests, swithes to production. 