stages:
- stage: CI
  jobs:
  - job: BuildAndTest
    pool:
      name: 'nevotek-agent'
      demands:
        - agent.name -equals nevotek-agent-001
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: $(nodeVersion)
    - script: |
        npm install
        npm run lint
        npm run test
        npm run test:integration
      displayName: 'Install, lint, and test'
    - script: npm run build
      displayName: 'Build application'
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-nonprod1927'
        repository: 'myrepo'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)
          latest