stages:
- stage: NotifyTester
  jobs:
  - job: CreateAndNotifyJiraIssue
    pool:
      name: 'nevotek-agent'
      demands:
        - agent.name -equals nevotek-agent-001
    steps:
    - template: tasks/create-jira-issue.yml
    - template: tasks/wait-for-approval.yml
      parameters:
        jiraIssueKey: $(createJiraIssue.JIRA_ISSUE_KEY)