stages:
- stage: Tests
  jobs:
  - job: SiteStatusCheck
    pool:
      name: 'nevotek-agent'
      demands:
        - agent.name -equals nevotek-agent-001
    steps:
    - script: |
        RESPONSE=$(curl --max-time 100 -o /dev/null -s -w "%{http_code}\n" https://nevotekapp-development.azurewebsites.net/)
        if [ $RESPONSE -ne 200 ]; then
          echo "Site is not reachable, returned status: $RESPONSE"
          exit 1
        fi
      displayName: 'Site Status Check (200 OK)'
      continueOnError: true